### PR TITLE
Updated the format via Html tags

### PR DESCRIPTION
**Pull request by sudheer51**

### CODE REVIEW

**Comment by hdabiri** [comment]
I approve this change

**Comment by srilunagalla** [comment]
I rejected

**Review by hdabiri — COMMENTED** [review]
here it is

**Review by srilunagalla — COMMENTED** [review]
I rejected

**Review by seemasinha — COMMENTED** [review]
Approved

**Review by sirishak9 — COMMENTED** [review]
Approved

**Review by Vijjiu — COMMENTED** [review]
I reject it. Not approved

**Review by sirishak9 — COMMENTED** [review]
Rejected

**Pull request merged**
